# Generated by Django 4.0.3 on 2022-08-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='class_name',
            new_name='className',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='dueDate',
        ),
    ]
